/* 
 * File:   cat_weapons.h
 * Author: jacksalien
 *
 * Created on January 19, 2015, 3:15 PM
 */

#ifndef CAT_WEAPONS_H
#define	CAT_WEAPONS_H

#include <vector>
#include <string>

std::vector<std::string> cat_weapons_vec({
"< 22LR ><10>",
"< 357MAG ><10>",
"< 38SPL ><10>",
"< 45ACP ><10>",
"< ADVOCATE ><10>",
"< ADVOCATES ><10>",
"< AK 47 ><15>",
"< AK47 ><15>",
"< AMMO ><10>",
"< AMMUNITION ><10>",
"< AR15 ><10>",
"< ARMALITE ><10>",
"< ARMORY ><10>",
"< ARTILLERY ><10>",
"< BELTFED ><10>",
"< BELT FED ><15>",
"< BENELLI ><10>",
"< BLACK POWDER ><10>",
"< BLACKPOWDER ><10>",
"< BLUEING ><10>",
"< BLUING ><10>",
"< BOLT ACTION ><10>",
"<BOMB BUILDING><70>",
"< BREN TEN ><10>",
"< BULLET ><15>",
"< BULLETS ><15>",
"< CALIBER ><10>",
"< CALIBERS ><10>",
"< CARBINE ><10>",
"< CENTERFIRE ><10>",
"< CHECKERING ><10>",
"< CONTROL ><10>",
"< CRUISE MISSILE ><10>",
"< CRUISE MISSILES ><10>",
"< DISKETTBOMB ><70>",
"< FIREARM ><10>",
"< FIREARMS ><10>",
"< FIRING PIN ><10>",
"< FLINTLOCK ><10>",
"< FLINTLOCKS ><10>",
"< GAROTTE ><10>",
"< GARROTE ><15>",
"< GLOCK ><10>",
"< GUN ><15>",
"<GUN MAKING><70>",
"< GUN POWDER ><10>",
"< GUNPOWDER ><10>",
"< GUN RANGE ><15>",
"< GUNRANGE ><15>",
"< GUNS ><15>",
"< GUNSHOP ><15>",
"< GUNSMITH ><15>",
"< GUNSMITHING ><15>",
"< HANDGUN ><10>",
"< HANDGUNS ><10>",
"< HANDLOADING ><10>",
"< HECKLER KOCK ><10>",
"< KAHR ><10>",
"< KNIFE ><15>",
"< KNIVES ><15>",
"< M16 ><10>",
"< MAC10 ><10>",
"< MACHINE GUN ><10>",
"< MACHINEGUN ><10>",
"< MACHINEGUNS ><10>",
"< MACHINE GUNS ><15>",
"< MARKSMANSHIP ><10>",
"< MAUSER ><10>",
"< MOSSBERG ><10>",
"< MUZZLELOADER ><10>",
"< MUZZLELOADING ><10>",
"< NRA ><10>",
"< ORDNANCE ><10>",
"< PARKERIZE ><10>",
"< PARKERIZING ><10>",
"< PISTOL ><10>",
"< PISTOLS ><10>",
"< PISTOLSMITH ><15>",
"< RADARJAMMING ><70>",
"< RECOIL BUFFER ><10>",
"< RECOIL BUFFERS ><10>",
"< REVOLVER ><10>",
"< REVOLVERS ><10>",
"< RIFLE ><10>",
"< RIFLES ><10>",
"< RIFLING ><10>",
"< RIMFIRE ><10>",
"< RUGER ><10>",
"< SAIGA ><10>",
"< SCHROTFLINTE ><10>",
"< SEMIAUTO ><10>",
"< SEMI AUTOMATIC ><10>",
"< SEMIAUTOMATIC ><10>",
"< SHOOTERS ><10>",
"< SHOOTING ><15>",
"< SHOOTIST ><10>",
"< SHOTGUN ><10>",
"< SHOTGUNS ><10>",
"< SHURIKEN ><10>",
"< SIDEARM ><10>",
"< SIDEARMS ><10>",
"< SIGARMS ><10>",
"< SMITH WESSON ><15>",
"< SNIPER ><10>",
"< SNIPING ><10>",
"< SPEEDLOADER ><10>",
"< STEYR ><10>",
"< SUB MACHINEGUN ><15>",
"< SUBMACHINEGUN ><15>",
"< SUB MACHINEGUNS ><15>",
"< SUBMACHINEGUNS ><15>",
"< SWORD ><10>",
"< SWORDS ><10>",
"< TACTICAL ><10>",
"< TEC9 ><10>",
"< TERRORISTHANDBOOK ><70>",
"< TERRORISTS HANDBOOK ><50>",
"< UZI ><10>",
"< WADCUTTER ><10>",
"< WALTHER ><10>",
"< WEAPON ><15>",
"< WEAPONS ><15>",
"< WINCHESTER ><10>",
"< FERTILIZER BOMB ><15>",
"< TRIIODIDE ><15>",
"< SOLIDOX ><15>",
"< THERMITE ><15>",
"< MOLITOFF COCKTAIL ><25>",
"< MOLITOV COCKTAIL ><25>",
"< MOLOTOV COCKTAIL ><25>"
});

#endif	/* CAT_WEAPONS_H */

