/* 
 * File:   cat_personals.h
 * Author: jacksalien
 *
 * Created on January 19, 2015, 3:06 PM
 */

#ifndef CAT_PERSONALS_H
#define	CAT_PERSONALS_H

#include <vector>
#include <string>

std::vector<std::string> cat_personals_vec({
"<ADULT PERSONALS><60>",
"<BROWSE MEN><20>",
"<BROWSE WOMEN><20>",
"<COUPLES SEEKING COUPLES><10>",
"<COUPLES SEEKING MEN><10>",
"<COUPLES SEEKING WOMEN><10>",
"<CUPID REPORT><30>",
"<CUPID SEARCH><30>",
"<DATING GUIDE><10>",
"<DATING SERVICE><30>",
"<DATING SITE><30>",
"<DISCREET RELATIONSHIP><20>",
"<FIND YOUR PERFECT MATCH><20>",
"<FIND YOUR PERFECT PARTNER><20>",
"<FOR SINGLE MEN AND WOMEN><20>",
"<FRIEND FINDER><20>",
"<FRIENDFINDER><30>",
"<FRIENDFINDER HANDLE><30>",
"<GAY PERSONALS><30>",
"<IDEAL PARTNER><10>",
"<LARGEST DATING SITE><30>",
"<LARGEST SINGLES SITE><50>",
"<LESBIAN PERSONALS><30>",
"<MEETING MEN><10>",
"<MEETING WOMEN><10>",
"<MEET SOMEONE SPECIAL><20>",
"<MEN SEEKING COUPLES><10>",
"<MEN SEEKING MEN><10>",
"<MEN SEEKING WOMEN><10>",
"<ONLINE DATING><30>",
"<PERSONAL AD><40>",
"<.PERSONALS><60>",
"<PERSONALS COMMUNITY><20>",
"<PERSONALS NETWORK><30>",
"<PHOTO PERSONALS><30>",
"<SEARCH FOR YOUR IDEAL PARTNER><50>",
"<SEARCH PERSONALS><30>",
"<SEEKING CASUAL SEX><30>",
"<SEEKING ROMANCE><10>",
"<SINGLES ONLINE><30>",
"<SINGLES SITE><30>",
"<SWINGERS DIRECTORY><50>",
"<WOMEN SEEKING COUPLES><10>",
"<WOMEN SEEKING MEN><10>",
"<WOMEN SEEKING WOMEN><10>",
"<YAHOO! PERSONALS><30>"
});

std::vector<std::string> cat_personals_double_vec({
"<I AM A>,<MAN>,<WOMAN>,<LOOKING FOR A><60>",
"<PERSONALS>,<DATING>,<ROMANCE>,<MARRIAGE><30>",
"<PERSONALS>,<MATCHMAKING><20>",
"<PERSONALS>,<SUCCESS STORIES><30>",
"<PERSONALS>,<SUCCESS STORY><30>",
"<PERSONALS>,<TESTIMONIAL><30>",
"<PHOTO SEARCH>,<PERSONALS><30>",
"<SEARCH>,<DATING>,<JOIN>,<IDEAL PARTNER><60>"
});

#endif	/* CAT_PERSONALS_H */

