/* 
 * File:   cat_secretsocieties.h
 * Author: jacksalien
 *
 * Created on January 19, 2015, 3:10 PM
 */

#ifndef CAT_SECRETSOCIETIES_H
#define	CAT_SECRETSOCIETIES_H

#include <vector>
#include <string>

std::vector<std::string> cat_secretsocieties_vec({
"<SECRET SOCIET><35>",
"<FRATERNAL ORDER><35>",
"<FRATERNAL SOCIETY><35>",
"<FRATERNAL ASSOCIATION><35>",
"<FRATERNAL LEAGUE><35>",
"<SUPERIOR GENERAL><35>",
"<UNITED ORDER><35>",
"<UNITED SOCIETY><35>",
"<UNITED ASSOCIATION><35>",
"<UNITED LEAGUE><35>",
"<UNION LEAGUE><35>",
"<BILDERBERG GROUP><45>",
"<SKULL AND BONES><45>",
"<SKULL & BONES><45>",
"<KU KLUX KLAN><45>",
"<LOYAL ORDER><45>",
"<JACOBIN><45>",
"<JOB'S DAUGHTERS><45>",
"<KNIGHTS OF THE GOLDEN EAGLE><45>",
"<JACOBITE><45>",
"<JESUIT ORDER><45>",
"<COMPANY OF SION><45>",
"<ILLUMINATI ><45>",
"<FIAT LUX><45>",
"<HIBERNIANS><45>",
"<THE RED MEN><45>",
"<FREEMASON><45>",
"<MASTER MASON><45>",
"<MASONIC><45>",
"<ODD FELLOWS><45>",
"<ROSICRUCIANS><45>",
"<ORDER OF EASTERN STAR><45>",
"<ORDER OF FORESTERS><45>",
"<ORDER OF FREESMITHS><45>",
"<ORDER OF GLEANERS><45>",
"<ORDER OF OWLS><45>",
"<ORDER OF THE><55>",
"<ORDER OF DRUIDS><45>",
"<LOYAL ORDER OF><30>",
"<INDEPENDENT ORDER OF><30>",
"<KNIGHTS OF PYTHIAS><45>",
"<KNIGHTS OF MALTA><45>",
"<KNIGHTS TEMPLAR><45>",
"<KNIGHTS OF THE HOLY SEPULCHRE><45>",
"<KNIGHTS OF THE HOLY CROSS><45>",
"<KNIGHTS OF THE GLOBE><45>",
"<KNIGHTS OF THE MIDNIGHT MYSTERY><45>",
"<KNIGHTS OF THE HONOR><45>"
});

std::vector<std::string> cat_secretsocieties_double_vec({
"< ELKS >,<PROTECTIVE><25>"
});

#endif	/* CAT_SECRETSOCIETIES_H */

